services:
  blog-loadtest:
    build: .
    image: blog-loadtest:latest
    container_name: blog-loadtest
    deploy:
      resources:
        limits:
          cpus: '1.25'
          memory: 2G
    ports:
      - "9003:9003"
    environment:
      - TZ=Asia/Seoul
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=Asia/Seoul
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - blog-network
      - my-network
      - load-test-net
    restart: unless-stopped

networks:
  blog-network:
    external: true
  my-network:
    external: true
  load-test-net:
    external: true